
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AIRDATE AIRDATELABEL ANSWERLABEL CATEGORIESLABEL CATEGORYLABEL COLON COMMA LBRACE LBRACKET NUMBER QUESTIONLABEL QUESTIONSLABEL RBRACE RBRACKET ROUND ROUNDLABEL SHOWNUMLABEL TEXT VALUE VALUELABELfile : LBRACE CATEGORIESLABEL COLON LBRACKET categories RBRACKET COMMA QUESTIONSLABEL COLON  LBRACKET questions RBRACKET RBRACEcategories : TEXT\n        | NUMBER\n        | TEXT COMMA categories\n        | NUMBER COMMA categoriesquestions : question\n                    | question COMMA questionsquestion : LBRACE category COMMA AIRDATELABEL COLON AIRDATE COMMA QUESTIONLABEL COLON TEXT COMMA VALUELABEL COLON VALUE COMMA answer COMMA ROUNDLABEL COLON ROUND COMMA SHOWNUMLABEL COLON NUMBER RBRACEcategory : CATEGORYLABEL COLON TEXT\n                | CATEGORYLABEL COLON NUMBER\n                | CATEGORYLABEL COLON VALUEanswer : ANSWERLABEL COLON TEXT\n            | ANSWERLABEL COLON NUMBER\n            | ANSWERLABEL COLON VALUE'
    
_lr_action_items = {'LBRACE':([0,17,24,],[2,18,18,]),'$end':([1,27,],[0,-1,]),'CATEGORIESLABEL':([2,],[3,]),'COLON':([3,15,22,29,36,40,45,48,55,],[4,16,26,33,37,41,47,52,56,]),'LBRACKET':([4,16,],[5,17,]),'TEXT':([5,10,11,26,37,47,],[7,7,7,30,38,49,]),'NUMBER':([5,10,11,26,47,56,],[8,8,8,31,50,57,]),'RBRACKET':([6,7,8,13,14,19,20,28,58,],[9,-2,-3,-4,-5,23,-6,-7,-8,]),'COMMA':([7,8,9,20,21,30,31,32,34,38,42,44,49,50,51,53,58,],[10,11,12,24,25,-9,-10,-11,35,39,43,46,-12,-13,-14,54,-8,]),'QUESTIONSLABEL':([12,],[15,]),'CATEGORYLABEL':([18,],[22,]),'RBRACE':([23,57,],[27,58,]),'AIRDATELABEL':([25,],[29,]),'VALUE':([26,41,47,],[32,42,51,]),'AIRDATE':([33,],[34,]),'QUESTIONLABEL':([35,],[36,]),'VALUELABEL':([39,],[40,]),'ANSWERLABEL':([43,],[45,]),'ROUNDLABEL':([46,],[48,]),'ROUND':([52,],[53,]),'SHOWNUMLABEL':([54,],[55,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'file':([0,],[1,]),'categories':([5,10,11,],[6,13,14,]),'questions':([17,24,],[19,28,]),'question':([17,24,],[20,20,]),'category':([18,],[21,]),'answer':([43,],[44,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> file","S'",1,None,None,None),
  ('file -> LBRACE CATEGORIESLABEL COLON LBRACKET categories RBRACKET COMMA QUESTIONSLABEL COLON LBRACKET questions RBRACKET RBRACE','file',13,'p_file','JTparser.py',157),
  ('categories -> TEXT','categories',1,'p_categories','JTparser.py',160),
  ('categories -> NUMBER','categories',1,'p_categories','JTparser.py',161),
  ('categories -> TEXT COMMA categories','categories',3,'p_categories','JTparser.py',162),
  ('categories -> NUMBER COMMA categories','categories',3,'p_categories','JTparser.py',163),
  ('questions -> question','questions',1,'p_questions','JTparser.py',170),
  ('questions -> question COMMA questions','questions',3,'p_questions','JTparser.py',171),
  ('question -> LBRACE category COMMA AIRDATELABEL COLON AIRDATE COMMA QUESTIONLABEL COLON TEXT COMMA VALUELABEL COLON VALUE COMMA answer COMMA ROUNDLABEL COLON ROUND COMMA SHOWNUMLABEL COLON NUMBER RBRACE','question',25,'p_question','JTparser.py',174),
  ('category -> CATEGORYLABEL COLON TEXT','category',3,'p_category','JTparser.py',182),
  ('category -> CATEGORYLABEL COLON NUMBER','category',3,'p_category','JTparser.py',183),
  ('category -> CATEGORYLABEL COLON VALUE','category',3,'p_category','JTparser.py',184),
  ('answer -> ANSWERLABEL COLON TEXT','answer',3,'p_answer','JTparser.py',188),
  ('answer -> ANSWERLABEL COLON NUMBER','answer',3,'p_answer','JTparser.py',189),
  ('answer -> ANSWERLABEL COLON VALUE','answer',3,'p_answer','JTparser.py',190),
]
